FROM golang:1.23-alpine AS builder

RUN apk add --no-cache gcc musl-dev

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=1 GOOS=linux go build -o main hello.go

FROM alpine:latest

RUN apk add --no-cache libc-dev

WORKDIR /app

COPY --from=builder /app/main .

RUN mkdir -p /app/data

EXPOSE 8080

CMD ["./main"]